---
title: MarcelVenema.com
baseURL: /
languageCode: en-US
defaultContentLanguage: en
theme: marcelvenema
# theme: mv-001

# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone: "Europe/Amsterdam"
# post pagination
paginate: 18 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength: 20 # see https://gohugo.io/content-management/excerpts/



canonifyURLs: false
disableAliases: true
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: false
enableRobotsTXT: true
rssLimit: 10
preserveTaxonomyNames: true
metaDataFormat: yaml
googleAnalytics: "G-BPYZWSQKWP" # example : UA-123-45
permalinks:
  pages: "/:slug/"
  page: /:slug/
  blog: "/post/:slug/"
  categories: "/blog/categories/:slug/"
taxonomies:
  tag: tags
  category: categories
  author: authors
disableKinds:
  - RSS
imaging:
  quality: 100
build:
  writeStats: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    style: solarized-dark256
    tabWidth: 4
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - REDIRECTS
    - HEADERS
  section:
    - HTML
#mediaTypes:
  #text/netlify:
  #  suffixes:
  #    - ""
  #  delimiter: ""
outputFormats:
  REDIRECTS:
    #mediaType: text/netlify
    mediaType: text/plain
    baseName: _redirects
    isPlainText: true
    notAlternative: true
  HEADERS:
    mediaType: text/plain
    baseName: _headers
    isPlainText: true
    notAlternative: true
  SITEMAP:
    mediaType: application/xml
    baseName: sitemap
    isHTML: false
    isPlainText: true
    noUgly: true
    rel: sitemap
caches:
  getjson:
    dir: ":cacheDir/:project"
    maxAge: 10s
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
minify:
  tdewolff:
    html:
      keepWhitespace: false
module:
  hugoVersion:
    extended: true
    min: 0.120.0

  mounts:
    - source: assets
      target: assets
    - source: static
      target: static
    - source: node_modules/alpinejs
      target: assets/js/vendor/alpinejs
    - source: node_modules/@alpinejs/collapse
      target: assets/js/vendor/collapse
    - source: node_modules/@alpinejs/persist
      target: assets/js/vendor/persist
    - source: node_modules/swiper
      target: assets/js/vendor/swiper
    - source: node_modules/infinite-scroll
      target: assets/js/vendor/infinite-scroll
    - source: node_modules/masonry-layout
      target: assets/js/vendor/masonry-layout
    - source: node_modules/minisearch
      target: assets/js/vendor/minisearch