############# English navigation ##############

# main menu
[[main]]
name = "HOME"
url = ""
weight = 10

[[main]]
name = "ABOUT"
url = "about/"
weight = 60

[[main]]
name = "BLOG"
url = "blog/"
weight = 20

[[main]]
name = "TRAINING"
url = "training/"
weight = 30

[[main]]
name = "TOOLS"
url = "tools/"
weight = 40

[[main]]
parent = "ABOUT"
name = "Elements"
url = "elements/"
weight = 61

[[main]]
parent = "ABOUT"
name = "Career"
url = "career/"

[[main]]
parent = "ABOUT"
name = "Pricing"
url = "pricing/"

[[main]]
parent = "ABOUT"
name = "Authors"
url = "authors/"

[[main]]
parent = "ABOUT"
name = "Contact"
url = "contact/"

[[main]]
parent = "ABOUT"
name = "Terms & Conditions"
url = "terms-conditions/"

[[main]]
parent = "ABOUT"
name = "404"
url = "404/"

# FOOTER


[[footer_01]]
name = "About MarcelVenema.com"
url = "about/"
weight = 10

[[footer_01]]
name = "Contact"
url = "contact/"
weight = 20

[[footer_01]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 30

[[footer_01]]
name = "Privacy policy"
url = "privacy-policy/"
weight = 40